title: Prabhat Labs
subtitle: "DevOPS and SRE Blog"
email: prabhatmaurya@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is collection of article base on my work on DevOps and SRE domain.
url: "https://prabhatmaurya.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/assets/images/mypic.jpg"
masthead_title: "Prabhat Labs"
breadcrumbs: true
show_date: true
twitter_username: prabhatmaurya
github_username:  prabhatmaurya
github: [metadata]
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
enable_copy_code_button: true
search: true
include:
  - "_pages"
plugins:
  - jekyll-feed
  - jekyll-include-cache

header:
  image: /assets/images/badami-temple.jpg
  image_description: "Galaganatha and Sangameshwara temples at Pattadakal"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      toc: false
author:
  name: "Prabhat Kumar"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an **SRE engg** and parttime 'Trekker'." # Note: Markdown is allowed
  location: "Bangalore"